---
title: "Combined Data"
output: html_document
date: "2024-07-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
# install.packages("devtools")
devtools::install_github("bio-oracle/biooracler")
library(biooracler)
library(tidyverse)
library(stars)
```


2020 ssp2 (45)
```{r}
#identifying data set for surface temperature
dataset_id = "thetao_ssp245_2020_2100_depthsurf"

time = c('2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.975, -74) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "thetao_mean"
              
#downloading layer for temp
temp_ssp2_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#identifying data set for depth 
dataset_id = "mlotst_ssp245_2020_2100_depthsurf"

time = c('2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.75, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "mlotst_mean"
              
# downloading layer
mld_ssp2_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#identifying data set for primary production 
dataset_id = "chl_ssp245_2020_2100_depthsurf"

time = c('2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z')

latitude = c(0, 58.21155) 
longitude = c(-179.975, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "chl_mean"
              
# downloading layer 
chl_ssp2_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```

2020 ssp 4 (60)
```{r}
#temperature 
dataset_id = "thetao_ssp460_2020_2100_depthsurf"

time = c('2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.975, -74) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "thetao_mean"
              
#downloading layer
temp_ssp4_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#depth
dataset_id = "mlotst_ssp460_2020_2100_depthsurf"

time = c('2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.75, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "mlotst_mean"
              
# download
mld_ssp4_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#primary production 
dataset_id = "chl_ssp460_2020_2100_depthsurf"

time = c('2020-01-01T00:00:00Z', '2020-01-01T00:00:00Z')

latitude = c(0, 58.21155) 
longitude = c(-179.975, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "chl_mean"
              
# download
chl_ssp4_2020 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```


2090 ssp2 (45)
```{r}
#temp
dataset_id = "thetao_ssp245_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.975, -74) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "thetao_mean"

#download
temp_2090_ssp2 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)


#depth
dataset_id = "mlotst_ssp245_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.75, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "mlotst_mean"
              
# download
mld_2090_ssp2 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#primary production 
dataset_id = "chl_ssp245_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(0, 58.21155) 
longitude = c(-179.975, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "chl_mean"
              
# download
chl_2090_ssp2 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```


2050 ssp2 (45)
```{r}
#identifying data set for surface temperature
dataset_id = "thetao_ssp245_2020_2100_depthsurf"

time = c('2050-01-01T00:00:00Z', '2050-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.975, -74) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "thetao_mean"
              
#downloading layer for temp
temp_ssp2_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#identifying data set for depth 
dataset_id = "mlotst_ssp245_2020_2100_depthsurf"

time = c('2050-01-01T00:00:00Z', '2050-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.75, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "mlotst_mean"
              
# downlaoding layer
mld_ssp2_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#identifying data set for primary production 
dataset_id = "chl_ssp245_2020_2100_depthsurf"

time = c('2050-01-01T00:00:00Z', '2050-01-01T00:00:00Z')

latitude = c(0, 58.21155) 
longitude = c(-179.975, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "chl_mean"
              
# downloading layer 
chl_ssp2_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```

2050 ssp 4 (60)
```{r}
#temperature 
dataset_id = "thetao_ssp460_2020_2100_depthsurf"

time = c('2050-01-01T00:00:00Z', '2050-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.975, -74) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "thetao_mean"
              
#downloading layer
temp_ssp4_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#depth
dataset_id = "mlotst_ssp460_2020_2100_depthsurf"

time = c('2050-01-01T00:00:00Z', '2050-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.75, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "mlotst_mean"
              
# download
mld_ssp4_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#primary production 
dataset_id = "chl_ssp460_2020_2100_depthsurf"

time = c('2050-01-01T00:00:00Z', '2050-01-01T00:00:00Z')

latitude = c(0, 58.21155) 
longitude = c(-179.975, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "chl_mean"
              
# download
chl_ssp4_2050 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```


2090 ssp2 (45)
```{r}
#temp
dataset_id = "thetao_ssp245_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.975, -74) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "thetao_mean"

#download
temp_2090_ssp2 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)


#depth
dataset_id = "mlotst_ssp245_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.75, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "mlotst_mean"
              
# download
mld_2090_ssp2 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#primary production 
dataset_id = "chl_ssp245_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(0, 58.21155) 
longitude = c(-179.975, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "chl_mean"
              
# download
chl_2090_ssp2 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
```


2090 ssp4 (60)
```{r}
#temp 
dataset_id = "thetao_ssp460_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.975, -74) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "thetao_mean"
              
# download
temp_2090_ssp4<- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#depth
dataset_id = "mlotst_ssp460_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(-58, 78) 
longitude = c(-179.75, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "mlotst_mean"
              
# download
mld_2090_ssp4 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)

#primary production 
dataset_id = "chl_ssp460_2020_2100_depthsurf"

time = c('2090-01-01T00:00:00Z', '2090-01-01T00:00:00Z')

latitude = c(0, 58.21155) 
longitude = c(-179.975, -76.9844) 

constraints = list(time, latitude, longitude)
names(constraints) = c("time", "latitude", "longitude")

variables = "chl_mean"
              
# download 
chl_2090_ssp4 <- download_layers(dataset_id = dataset_id, variables = variables, constraints = constraints)
````


